--
-- PostgreSQL database dump
--

-- Dumped from database version 18.2
-- Dumped by pg_dump version 18.2
-- Nota: se quitaron \restrict/\unrestrict y "transaction_timeout" (solo
-- existen desde PostgreSQL 17+) para que este script funcione también
-- contra la imagen postgres:16-alpine usada en docker-compose.

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: administrador; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.administrador (
    id_administrador integer NOT NULL,
    nombres character varying(100) NOT NULL,
    correo character varying(100) NOT NULL,
    usuario character varying(50) NOT NULL,
    contrasena character varying(255) NOT NULL
);


--
-- Name: administrador_id_administrador_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.administrador_id_administrador_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: administrador_id_administrador_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.administrador_id_administrador_seq OWNED BY public.administrador.id_administrador;


--
-- Name: agenda_medica; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agenda_medica (
    id_agenda integer NOT NULL,
    id_medico integer NOT NULL,
    fecha date NOT NULL,
    hora_inicio time without time zone NOT NULL,
    hora_fin time without time zone NOT NULL,
    tipo_turno character varying(30) DEFAULT 'REGULAR'::character varying NOT NULL,
    estado character varying(20) DEFAULT 'DISPONIBLE'::character varying NOT NULL
);


--
-- Name: agenda_medica_id_agenda_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.agenda_medica_id_agenda_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: agenda_medica_id_agenda_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.agenda_medica_id_agenda_seq OWNED BY public.agenda_medica.id_agenda;


--
-- Name: cita; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cita (
    id_cita integer NOT NULL,
    id_paciente integer NOT NULL,
    id_medico integer NOT NULL,
    id_agenda integer NOT NULL,
    fecha date NOT NULL,
    hora_inicio time without time zone NOT NULL,
    hora_fin time without time zone NOT NULL,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    duracion_minutos integer NOT NULL,
    modalidad character varying(20) NOT NULL,
    estado character varying(20) DEFAULT 'PROGRAMADA'::character varying NOT NULL,
    motivo_consulta character varying(255)
);


--
-- Name: cita_id_cita_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.cita_id_cita_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: cita_id_cita_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.cita_id_cita_seq OWNED BY public.cita.id_cita;


--
-- Name: consulta_medica; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.consulta_medica (
    id_consulta integer NOT NULL,
    id_cita integer NOT NULL,
    id_historial integer NOT NULL,
    fecha_atencion timestamp without time zone NOT NULL,
    diagnostico text,
    observaciones text,
    tratamiento text
);


--
-- Name: consulta_medica_id_consulta_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.consulta_medica_id_consulta_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: consulta_medica_id_consulta_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.consulta_medica_id_consulta_seq OWNED BY public.consulta_medica.id_consulta;


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: especialidad; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.especialidad (
    id_especialidad integer NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion character varying(255),
    estado character varying(20) DEFAULT 'ACTIVA'::character varying NOT NULL
);


--
-- Name: especialidad_id_especialidad_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.especialidad_id_especialidad_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: especialidad_id_especialidad_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.especialidad_id_especialidad_seq OWNED BY public.especialidad.id_especialidad;


--
-- Name: historial_medico; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.historial_medico (
    id_historial integer NOT NULL,
    id_paciente integer NOT NULL,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    estado character varying(20) DEFAULT 'ACTIVO'::character varying NOT NULL
);


--
-- Name: historial_medico_id_historial_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.historial_medico_id_historial_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: historial_medico_id_historial_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.historial_medico_id_historial_seq OWNED BY public.historial_medico.id_historial;


--
-- Name: medico; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.medico (
    id_medico integer NOT NULL,
    id_especialidad integer NOT NULL,
    id_sede integer NOT NULL,
    nombres character varying(100) NOT NULL,
    apellidos character varying(100) NOT NULL,
    cmp character varying(20) NOT NULL,
    correo character varying(100) NOT NULL,
    telefono character varying(20),
    estado character varying(20) DEFAULT 'ACTIVO'::character varying NOT NULL,
    contrasena character varying(255)
);


--
-- Name: medico_id_medico_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.medico_id_medico_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: medico_id_medico_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.medico_id_medico_seq OWNED BY public.medico.id_medico;


--
-- Name: nota_medica; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nota_medica (
    id_nota integer NOT NULL,
    id_consulta integer NOT NULL,
    id_medico integer NOT NULL,
    descripcion text NOT NULL,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: nota_medica_id_nota_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.nota_medica_id_nota_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: nota_medica_id_nota_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.nota_medica_id_nota_seq OWNED BY public.nota_medica.id_nota;


--
-- Name: notificacion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notificacion (
    id_notificacion integer NOT NULL,
    id_paciente integer NOT NULL,
    id_cita integer NOT NULL,
    mensaje character varying(255) NOT NULL,
    tipo character varying(50) NOT NULL,
    canal character varying(30) NOT NULL,
    fecha_envio timestamp without time zone NOT NULL,
    estado character varying(20) NOT NULL
);


--
-- Name: notificacion_id_notificacion_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.notificacion_id_notificacion_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: notificacion_id_notificacion_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.notificacion_id_notificacion_seq OWNED BY public.notificacion.id_notificacion;


--
-- Name: paciente; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.paciente (
    id_paciente integer NOT NULL,
    nombres character varying(100) NOT NULL,
    apellidos character varying(100) NOT NULL,
    dni character varying(20) NOT NULL,
    correo character varying(100) NOT NULL,
    telefono character varying(20),
    direccion character varying(150),
    fecha_nacimiento date,
    estado character varying(20) DEFAULT 'ACTIVO'::character varying NOT NULL,
    contrasena character varying(255)
);


--
-- Name: paciente_id_paciente_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.paciente_id_paciente_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: paciente_id_paciente_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.paciente_id_paciente_seq OWNED BY public.paciente.id_paciente;


--
-- Name: plantilla_horario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plantilla_horario (
    id_plantilla integer NOT NULL,
    id_medico integer NOT NULL,
    dia_semana smallint NOT NULL,
    hora_inicio time without time zone NOT NULL,
    hora_fin time without time zone NOT NULL,
    tipo_turno character varying(30) DEFAULT 'REGULAR'::character varying NOT NULL,
    CONSTRAINT plantilla_horario_check CHECK ((hora_fin > hora_inicio)),
    CONSTRAINT plantilla_horario_dia_semana_check CHECK (((dia_semana >= 0) AND (dia_semana <= 6)))
);


--
-- Name: plantilla_horario_id_plantilla_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.plantilla_horario_id_plantilla_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: plantilla_horario_id_plantilla_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.plantilla_horario_id_plantilla_seq OWNED BY public.plantilla_horario.id_plantilla;


--
-- Name: sede; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sede (
    id_sede integer NOT NULL,
    nombre character varying(100) NOT NULL,
    direccion character varying(150) NOT NULL,
    telefono character varying(20),
    estado character varying(20) DEFAULT 'ACTIVA'::character varying NOT NULL
);


--
-- Name: sede_id_sede_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sede_id_sede_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sede_id_sede_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sede_id_sede_seq OWNED BY public.sede.id_sede;


--
-- Name: solicitud_disponibilidad; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.solicitud_disponibilidad (
    id_solicitud integer NOT NULL,
    id_medico integer NOT NULL,
    tipo character varying(20) NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    hora_inicio time without time zone,
    hora_fin time without time zone,
    motivo character varying(255) NOT NULL,
    estado character varying(20) DEFAULT 'PENDIENTE'::character varying NOT NULL,
    fecha_solicitud timestamp without time zone NOT NULL,
    fecha_resolucion timestamp without time zone,
    comentario_admin character varying(255)
);


--
-- Name: solicitud_disponibilidad_id_solicitud_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.solicitud_disponibilidad_id_solicitud_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: solicitud_disponibilidad_id_solicitud_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.solicitud_disponibilidad_id_solicitud_seq OWNED BY public.solicitud_disponibilidad.id_solicitud;


--
-- Name: vista_dataset_ml; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.vista_dataset_ml AS
 WITH demanda_agrupada AS (
         SELECT c.fecha AS "Fecha",
            e.nombre AS "Especialidad",
                CASE
                    WHEN (c.hora_inicio >= '18:00:00'::time without time zone) THEN 'After Office'::text
                    WHEN (c.hora_inicio >= '12:00:00'::time without time zone) THEN 'Tarde'::text
                    ELSE 'Mañana'::text
                END AS "PreferenciaHoraria",
                CASE EXTRACT(dow FROM c.fecha)
                    WHEN 1 THEN 'Lunes'::text
                    WHEN 2 THEN 'Martes'::text
                    WHEN 3 THEN 'Miércoles'::text
                    WHEN 4 THEN 'Jueves'::text
                    WHEN 5 THEN 'Viernes'::text
                    WHEN 6 THEN 'Sábado'::text
                    WHEN 0 THEN 'Domingo'::text
                    ELSE NULL::text
                END AS "DiaSemana",
            count(*) AS "Demanda"
           FROM ((public.cita c
             JOIN public.medico m ON ((c.id_medico = m.id_medico)))
             JOIN public.especialidad e ON ((m.id_especialidad = e.id_especialidad)))
          GROUP BY c.fecha, e.nombre,
                CASE
                    WHEN (c.hora_inicio >= '18:00:00'::time without time zone) THEN 'After Office'::text
                    WHEN (c.hora_inicio >= '12:00:00'::time without time zone) THEN 'Tarde'::text
                    ELSE 'Mañana'::text
                END,
                CASE EXTRACT(dow FROM c.fecha)
                    WHEN 1 THEN 'Lunes'::text
                    WHEN 2 THEN 'Martes'::text
                    WHEN 3 THEN 'Miércoles'::text
                    WHEN 4 THEN 'Jueves'::text
                    WHEN 5 THEN 'Viernes'::text
                    WHEN 6 THEN 'Sábado'::text
                    WHEN 0 THEN 'Domingo'::text
                    ELSE NULL::text
                END
        ), dataset_final AS (
         SELECT demanda_agrupada."Fecha",
            demanda_agrupada."Especialidad",
            demanda_agrupada."PreferenciaHoraria",
            demanda_agrupada."DiaSemana",
            COALESCE(lag(demanda_agrupada."Demanda") OVER (PARTITION BY demanda_agrupada."Especialidad", demanda_agrupada."PreferenciaHoraria", demanda_agrupada."DiaSemana" ORDER BY demanda_agrupada."Fecha"), demanda_agrupada."Demanda") AS "HistoricoDemanda",
            demanda_agrupada."Demanda"
           FROM demanda_agrupada
        )
 SELECT "Fecha",
    "Especialidad",
    "PreferenciaHoraria",
    "DiaSemana",
    "HistoricoDemanda",
    "Demanda"
   FROM dataset_final;


--
-- Name: administrador id_administrador; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administrador ALTER COLUMN id_administrador SET DEFAULT nextval('public.administrador_id_administrador_seq'::regclass);


--
-- Name: agenda_medica id_agenda; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_medica ALTER COLUMN id_agenda SET DEFAULT nextval('public.agenda_medica_id_agenda_seq'::regclass);


--
-- Name: cita id_cita; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cita ALTER COLUMN id_cita SET DEFAULT nextval('public.cita_id_cita_seq'::regclass);


--
-- Name: consulta_medica id_consulta; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consulta_medica ALTER COLUMN id_consulta SET DEFAULT nextval('public.consulta_medica_id_consulta_seq'::regclass);


--
-- Name: especialidad id_especialidad; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.especialidad ALTER COLUMN id_especialidad SET DEFAULT nextval('public.especialidad_id_especialidad_seq'::regclass);


--
-- Name: historial_medico id_historial; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_medico ALTER COLUMN id_historial SET DEFAULT nextval('public.historial_medico_id_historial_seq'::regclass);


--
-- Name: medico id_medico; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medico ALTER COLUMN id_medico SET DEFAULT nextval('public.medico_id_medico_seq'::regclass);


--
-- Name: nota_medica id_nota; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nota_medica ALTER COLUMN id_nota SET DEFAULT nextval('public.nota_medica_id_nota_seq'::regclass);


--
-- Name: notificacion id_notificacion; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacion ALTER COLUMN id_notificacion SET DEFAULT nextval('public.notificacion_id_notificacion_seq'::regclass);


--
-- Name: paciente id_paciente; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.paciente ALTER COLUMN id_paciente SET DEFAULT nextval('public.paciente_id_paciente_seq'::regclass);


--
-- Name: plantilla_horario id_plantilla; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plantilla_horario ALTER COLUMN id_plantilla SET DEFAULT nextval('public.plantilla_horario_id_plantilla_seq'::regclass);


--
-- Name: sede id_sede; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sede ALTER COLUMN id_sede SET DEFAULT nextval('public.sede_id_sede_seq'::regclass);


--
-- Name: solicitud_disponibilidad id_solicitud; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitud_disponibilidad ALTER COLUMN id_solicitud SET DEFAULT nextval('public.solicitud_disponibilidad_id_solicitud_seq'::regclass);


--
-- Name: administrador administrador_correo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administrador
    ADD CONSTRAINT administrador_correo_key UNIQUE (correo);


--
-- Name: administrador administrador_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administrador
    ADD CONSTRAINT administrador_pkey PRIMARY KEY (id_administrador);


--
-- Name: administrador administrador_usuario_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.administrador
    ADD CONSTRAINT administrador_usuario_key UNIQUE (usuario);


--
-- Name: agenda_medica agenda_medica_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_medica
    ADD CONSTRAINT agenda_medica_pkey PRIMARY KEY (id_agenda);


--
-- Name: cita cita_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cita
    ADD CONSTRAINT cita_pkey PRIMARY KEY (id_cita);


--
-- Name: consulta_medica consulta_medica_id_cita_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consulta_medica
    ADD CONSTRAINT consulta_medica_id_cita_key UNIQUE (id_cita);


--
-- Name: consulta_medica consulta_medica_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consulta_medica
    ADD CONSTRAINT consulta_medica_pkey PRIMARY KEY (id_consulta);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: especialidad especialidad_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.especialidad
    ADD CONSTRAINT especialidad_nombre_key UNIQUE (nombre);


--
-- Name: especialidad especialidad_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.especialidad
    ADD CONSTRAINT especialidad_pkey PRIMARY KEY (id_especialidad);


--
-- Name: historial_medico historial_medico_id_paciente_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_medico
    ADD CONSTRAINT historial_medico_id_paciente_key UNIQUE (id_paciente);


--
-- Name: historial_medico historial_medico_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_medico
    ADD CONSTRAINT historial_medico_pkey PRIMARY KEY (id_historial);


--
-- Name: medico medico_cmp_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT medico_cmp_key UNIQUE (cmp);


--
-- Name: medico medico_correo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT medico_correo_key UNIQUE (correo);


--
-- Name: medico medico_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT medico_pkey PRIMARY KEY (id_medico);


--
-- Name: nota_medica nota_medica_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nota_medica
    ADD CONSTRAINT nota_medica_pkey PRIMARY KEY (id_nota);


--
-- Name: notificacion notificacion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacion
    ADD CONSTRAINT notificacion_pkey PRIMARY KEY (id_notificacion);


--
-- Name: paciente paciente_correo_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT paciente_correo_key UNIQUE (correo);


--
-- Name: paciente paciente_dni_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT paciente_dni_key UNIQUE (dni);


--
-- Name: paciente paciente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.paciente
    ADD CONSTRAINT paciente_pkey PRIMARY KEY (id_paciente);


--
-- Name: plantilla_horario plantilla_horario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plantilla_horario
    ADD CONSTRAINT plantilla_horario_pkey PRIMARY KEY (id_plantilla);


--
-- Name: sede sede_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sede
    ADD CONSTRAINT sede_pkey PRIMARY KEY (id_sede);


--
-- Name: solicitud_disponibilidad solicitud_disponibilidad_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitud_disponibilidad
    ADD CONSTRAINT solicitud_disponibilidad_pkey PRIMARY KEY (id_solicitud);


--
-- Name: idx_plantilla_horario_medico; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plantilla_horario_medico ON public.plantilla_horario USING btree (id_medico);


--
-- Name: agenda_medica agenda_medica_id_medico_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agenda_medica
    ADD CONSTRAINT agenda_medica_id_medico_fkey FOREIGN KEY (id_medico) REFERENCES public.medico(id_medico);


--
-- Name: cita cita_id_agenda_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cita
    ADD CONSTRAINT cita_id_agenda_fkey FOREIGN KEY (id_agenda) REFERENCES public.agenda_medica(id_agenda);


--
-- Name: cita cita_id_medico_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cita
    ADD CONSTRAINT cita_id_medico_fkey FOREIGN KEY (id_medico) REFERENCES public.medico(id_medico);


--
-- Name: cita cita_id_paciente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cita
    ADD CONSTRAINT cita_id_paciente_fkey FOREIGN KEY (id_paciente) REFERENCES public.paciente(id_paciente);


--
-- Name: consulta_medica consulta_medica_id_cita_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consulta_medica
    ADD CONSTRAINT consulta_medica_id_cita_fkey FOREIGN KEY (id_cita) REFERENCES public.cita(id_cita);


--
-- Name: consulta_medica consulta_medica_id_historial_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.consulta_medica
    ADD CONSTRAINT consulta_medica_id_historial_fkey FOREIGN KEY (id_historial) REFERENCES public.historial_medico(id_historial);


--
-- Name: historial_medico historial_medico_id_paciente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.historial_medico
    ADD CONSTRAINT historial_medico_id_paciente_fkey FOREIGN KEY (id_paciente) REFERENCES public.paciente(id_paciente);


--
-- Name: medico medico_id_especialidad_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT medico_id_especialidad_fkey FOREIGN KEY (id_especialidad) REFERENCES public.especialidad(id_especialidad);


--
-- Name: medico medico_id_sede_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medico
    ADD CONSTRAINT medico_id_sede_fkey FOREIGN KEY (id_sede) REFERENCES public.sede(id_sede);


--
-- Name: nota_medica nota_medica_id_consulta_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nota_medica
    ADD CONSTRAINT nota_medica_id_consulta_fkey FOREIGN KEY (id_consulta) REFERENCES public.consulta_medica(id_consulta);


--
-- Name: nota_medica nota_medica_id_medico_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nota_medica
    ADD CONSTRAINT nota_medica_id_medico_fkey FOREIGN KEY (id_medico) REFERENCES public.medico(id_medico);


--
-- Name: notificacion notificacion_id_cita_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacion
    ADD CONSTRAINT notificacion_id_cita_fkey FOREIGN KEY (id_cita) REFERENCES public.cita(id_cita);


--
-- Name: notificacion notificacion_id_paciente_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notificacion
    ADD CONSTRAINT notificacion_id_paciente_fkey FOREIGN KEY (id_paciente) REFERENCES public.paciente(id_paciente);


--
-- Name: plantilla_horario plantilla_horario_id_medico_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plantilla_horario
    ADD CONSTRAINT plantilla_horario_id_medico_fkey FOREIGN KEY (id_medico) REFERENCES public.medico(id_medico);


--
-- Name: solicitud_disponibilidad solicitud_disponibilidad_id_medico_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.solicitud_disponibilidad
    ADD CONSTRAINT solicitud_disponibilidad_id_medico_fkey FOREIGN KEY (id_medico) REFERENCES public.medico(id_medico);


--
-- PostgreSQL database dump complete
--

