from django.urls import path

from citas import views


urlpatterns = [
    path("api/health/", views.health),
    path("api/auth/login/", views.login),
    path("api/auth/registro/", views.registrar_paciente),
    path("api/me/", views.me),
    path("api/catalogo/", views.catalogo),
    path("api/medicos/crear/", views.crear_medico),
    path("api/horarios/", views.horarios_medico),
    path("api/horarios/crear/", views.crear_horarios),
    path("api/horarios/<int:horario_id>/eliminar/", views.eliminar_horario),
    path("api/plantilla-horario/", views.plantilla_horario),
    path("api/plantilla-horario/crear/", views.crear_bloque_plantilla),
    path("api/plantilla-horario/<int:bloque_id>/eliminar/", views.eliminar_bloque_plantilla),
    path("api/plantilla-horario/aplicar/", views.aplicar_plantilla),
    path("api/recomendacion-horarios/", views.recomendacion_horarios),
    path("api/pacientes/<int:paciente_id>/", views.paciente_detalle),
    path("api/notificaciones/mias/", views.mis_notificaciones),
    path("api/dashboard/", views.dashboard),
    path("api/citas/", views.citas),
    path("api/citas/crear/", views.crear_cita),
    path("api/citas/<int:cita_id>/asistir/", views.marcar_asistido),
    path("api/citas/<int:cita_id>/solicitar-cancelacion/", views.solicitar_cancelacion),
    path("api/citas/<int:cita_id>/retirar-cancelacion/", views.retirar_cancelacion),
    path("api/citas/<int:cita_id>/aprobar-cancelacion/", views.aprobar_cancelacion),
    path("api/citas/<int:cita_id>/rechazar-cancelacion/", views.rechazar_cancelacion),
    path("api/citas/<int:cita_id>/cambiar-estado/", views.cambiar_estado_cita),
    path("api/citas/<int:cita_id>/reprogramar/", views.reprogramar_cita),
    path("api/citas/<int:cita_id>/marcar-contactado/", views.marcar_contactado),
    path("api/citas/<int:cita_id>/anular/", views.anular_cita),
    path("api/disponibilidad/solicitar/", views.solicitar_disponibilidad),
    path("api/disponibilidad/mias/", views.mis_solicitudes_disponibilidad),
    path("api/disponibilidad/", views.solicitudes_disponibilidad),
    path("api/disponibilidad/<int:solicitud_id>/aprobar/", views.aprobar_disponibilidad),
    path("api/disponibilidad/<int:solicitud_id>/rechazar/", views.rechazar_disponibilidad),
    path("api/disponibilidad/<int:solicitud_id>/cancelar/", views.cancelar_solicitud_disponibilidad),
]
